Repository MomirMilutinovic/graph-expressiveness-team-6, pull requests merged in 2024-02, with the labels that each got.

#15 Feature: Graph, Visualizer and Data Source API
  .gitignore
  api/__init__.py
  api/components/data_source.py
  api/components/visualizer.py
  api/models/edge.py
  api/models/graph.py
  api/models/node.py
Labels: enhancement, api

#21 Add pyproject.toml to the api package so it can be installed
  api/pyproject.toml
Labels: bugfix

#22 Spotify Datasource
  spotify_datasource/pyproject.toml
  spotify_datasource/src/spotify_datasource/__init__.py
  spotify_datasource/src/spotify_datasource/implementation.py
  spotify_datasource/src/spotify_datasource/models.py
  spotify_datasource/src/spotify_datasource/services.py
  spotify_datasource/src/spotify_datasource/utils.py
Labels: data source plugin

#18 Feature: HTML Data Source
  html_datasource/pyproject.toml
  html_datasource/requirements.txt
  html_datasource/src/__init__.py
  html_datasource/src/html_datasource/__init__.py
  html_datasource/src/html_datasource/implementation.py
Labels: data source plugin

#23 Tree View
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
Labels: platform

#26 Feature: Load Plugins
  core-sok/__init__.py
  core-sok/pyproject.toml
  core-sok/src/core/__init__.py
  core-sok/src/core/infrastructure.py
  graph_explorer/pyproject.toml
  graph_explorer/src/graph_explorer/graph_visualizer/apps.py
  html_datasource/pyproject.toml
Labels: platform

#28 Feature: Views Implementation
  api/models/node.py
  graph_explorer/src/graph_explorer/graph_visualizer/module/__init__.py
  graph_explorer/src/graph_explorer/graph_visualizer/module/content.py
  graph_explorer/src/graph_explorer/graph_visualizer/static/script.js
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: platform

#30 Simple visualizer plugin
  requirements.txt
  simple_visualizer/MANIFEST.in
  simple_visualizer/pyproject.toml
  simple_visualizer/src/simple_visualizer/__init__.py
  simple_visualizer/src/simple_visualizer/implementation.py
  simple_visualizer/src/simple_visualizer/templates/simple_visualizer_template.html
Labels: visualization plugin

#31 Upgrade Advanced Visualizer to D3 v7
  advanced_visualizer/src/templates/advanced_visualizer.html
Labels: visualization plugin

#35 Fix Node Addition
  api/models/graph.py
Labels: bug

#36 Workspaces
  advanced_visualizer/MANIFEST.in
  graph_explorer/src/graph_explorer/db.sqlite3
  graph_explorer/src/graph_explorer/graph_visualizer/apps.py
  graph_explorer/src/graph_explorer/graph_visualizer/models.py
  graph_explorer/src/graph_explorer/graph_visualizer/services.py
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/base.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/workspace_config.html
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: enhancement, platform

#40 Refactor: HTML Data Source
  html_datasource/requirements.txt
  html_datasource/src/html_datasource/implementation.py
  html_datasource/src/html_datasource/services.py
  html_datasource/src/html_datasource/utils.py
  html_datasource/src/main.py
Labels: refactor

#42 Graph Hotfix
  api/models/graph.py
Labels: bug, bugfix

#38 Feature: Search
  api/models/node.py
  core-sok/src/core/filters/__init__.py
  core-sok/src/core/filters/base_filter.py
  core-sok/src/core/filters/filter_chain.py
  core-sok/src/core/filters/filter_chain_tests.py
  core-sok/src/core/filters/search_filter.py
  core-sok/src/core/filters/search_filter_tests.py
  graph_explorer/src/graph_explorer/graph_visualizer/models.py
  graph_explorer/src/graph_explorer/graph_visualizer/module/content.py
  graph_explorer/src/graph_explorer/graph_visualizer/static/script.js
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: platform

#41 Simple viusalizer support for node ids that contain hashes
  simple_visualizer/src/simple_visualizer/templates/simple_visualizer_template.html
Labels: bugfix

#44 Refactor: Remove new line in text data
  html_datasource/src/html_datasource/utils.py
Labels: refactor

#46 Tree View Population
  graph_explorer/src/graph_explorer/graph_visualizer/models.py
  graph_explorer/src/graph_explorer/graph_visualizer/services.py
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
  spotify_datasource/src/spotify_datasource/implementation.py
Labels: enhancement, platform

#48 Feature: HTML Data Source Cyclic Support
  html_datasource/src/html_datasource/services.py
Labels: data source plugin

#45 Feature: Filtering
  core-sok/src/core/filters/operator_filter.py
  core-sok/src/core/filters/operator_filter_tests.py
  core-sok/src/core/filters/search_filter.py
  graph_explorer/src/graph_explorer/graph_visualizer/module/content.py
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: platform

#51 Avoid Exception on Tree View When There is No Data
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
Labels: bug, platform, bugfix

#53 Bash script that installs all plugins and runs the app.
  installAndRun.sh
Labels: enhancement

#49 Implement Bird View
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/bird_view.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
Labels: platform

#56 Fix Tree View Node Offset
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
Labels: bug, platform, bugfix

#58 Graph API Directionality
  api/models/edge.py
  api/models/graph.py
  api/models/node.py
Labels: enhancement, api

#59 Spotify Data Source Undirected Graph Support
  spotify_datasource/src/spotify_datasource/services.py
Labels: enhancement, data source plugin

#60 HTML Data Source Directed Graph Support
  html_datasource/src/html_datasource/services.py
Labels: enhancement, data source plugin

#57 Feature: Create API package
  api-sok/__init__.py
  api-sok/pyproject.toml
  api-sok/src/api/__init__.py
  api-sok/src/api/components/__init__.py
  api-sok/src/api/components/data_source.py
  api-sok/src/api/components/visualizer.py
  api-sok/src/api/models/__init__.py
  api-sok/src/api/models/edge.py
  api-sok/src/api/models/graph.py
  api-sok/src/api/models/node.py
  installAndRun.sh
Labels: api, refactor

#62 Feature: Documentation
  README.md
  installAndRun.bat
Labels: documentation

#66 Fix UI Design Problems
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/bird_view.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
Labels: bug, platform, bugfix

#61 Fix Index Redirection
  graph_explorer/src/graph_explorer/graph_visualizer/services.py
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: bug, platform, bugfix

#63 Implement Edit and Delete Buttons for Workspace
  graph_explorer/src/graph_explorer/graph_visualizer/apps.py
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/workspace_config.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/workspace_edit.html
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: platform

#64 Contains Filter for Lists
  api-sok/src/api/models/graph.py
  core-sok/src/core/filters/filter_pipeline.py
  core-sok/src/core/filters/filter_pipeline_tests.py
  core-sok/src/core/filters/operator_filter.py
  core-sok/src/core/filters/operator_filter_tests.py
  core-sok/src/core/filters/search_filter.py
  core-sok/src/core/filters/search_filter_tests.py
  graph_explorer/src/graph_explorer/graph_visualizer/models.py
  graph_explorer/src/graph_explorer/graph_visualizer/services.py
  graph_explorer/src/graph_explorer/graph_visualizer/static/script.js
  graph_explorer/src/graph_explorer/graph_visualizer/static/style.css
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: platform

#67 Add Support for Undirected Graphs in Advanced Visualizer
  advanced_visualizer/src/advanced_visualizer/implementation.py
  advanced_visualizer/src/templates/advanced_visualizer.html
Labels: enhancement, visualization plugin

#68 Graph Root
  api-sok/src/api/models/graph.py
  graph_explorer/src/graph_explorer/graph_visualizer/models.py
  graph_explorer/src/graph_explorer/graph_visualizer/services.py
  spotify_datasource/src/spotify_datasource/services.py
Labels: enhancement, api

#69 Feature: HTML Graph Root
  html_datasource/src/html_datasource/services.py
Labels: data source plugin

#73 Simple visualizer arrowheads
  simple_visualizer/src/simple_visualizer/implementation.py
  simple_visualizer/src/simple_visualizer/templates/simple_visualizer_template.html
Labels: enhancement

#75 Fix Spotify Data Source Max Neighbours
  spotify_datasource/src/spotify_datasource/services.py
Labels: bug, data source plugin, bugfix

#78 Decrease gravity in simple visualizer
  simple_visualizer/src/simple_visualizer/templates/simple_visualizer_template.html
Labels: bugfix

#79 Fix Search Functionality for Case Without Active Workspace
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
Labels: bug, platform, bugfix

#80 Disable filtering if no workspace is selected
  graph_explorer/src/graph_explorer/graph_visualizer/templates/index.html
Labels: bugfix

#81 Don't display the names of focused nodes in bold in simple visualizer
  simple_visualizer/src/simple_visualizer/templates/simple_visualizer_template.html
Labels: bugfix

#77 Core Refactor
  advanced_visualizer/src/templates/advanced_visualizer.html
  core-sok/src/core/content.py
  core-sok/src/core/models.py
  core-sok/src/core/services.py
  graph_explorer/src/graph_explorer/graph_visualizer/apps.py
  graph_explorer/src/graph_explorer/graph_visualizer/module/__init__.py
  graph_explorer/src/graph_explorer/graph_visualizer/module/content.py
  graph_explorer/src/graph_explorer/graph_visualizer/services.py
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
  graph_explorer/src/graph_explorer/graph_visualizer/urls.py
  graph_explorer/src/graph_explorer/graph_visualizer/views.py
Labels: enhancement, platform

#82 Api Docs
  api-sok/src/api/components/data_source.py
  api-sok/src/api/components/visualizer.py
  api-sok/src/api/models/edge.py
  api-sok/src/api/models/graph.py
  api-sok/src/api/models/node.py
Labels: documentation, api

#83 Required Workspace Form Config Fields
  graph_explorer/src/graph_explorer/graph_visualizer/templates/workspace_config.html
Labels: enhancement, platform

#84 Prevent Exception When Ancestors Are Undefined
  advanced_visualizer/src/templates/advanced_visualizer.html
  graph_explorer/src/graph_explorer/graph_visualizer/templates/tree_view.html
Labels: bug, platform, bugfix

#85 Feature: Add Needed Images
  README.md
  assets/component_diagram.jpg
  assets/simple_visualizer.jpg
  assets/spotify_datasource.jpg
Labels: documentation

#86 Update Spotify DS Docs
  README.md
Labels: documentation, enhancement
